Create and use HISTORIC_RANGE_DEFAULT in extra params components
azavea/climate-change-components pull request #15
Opened 2017-11-20 20:54 UTC by CloudNiner

Value of HISTORIC_RANGE_DEFAULT matches default historic_range
param value of the Climate API

## Overview

Updates the historic range param controls to just automatically set themselves to the same value that the Climate API defaults to (1971) without presenting a "blank" option, since the API selects a default anyways if no param value is provided. This reduces confusion as to what the dropdown options mean in the Lab.

### Demo

Both screenshots taken after selecting the indicator shown. No further actions taken to select extra params values:

![screen shot 2017-11-20 at 15 48 23](https://user-images.githubusercontent.com/1818302/33040887-7f2fb53e-ce0a-11e7-931f-259ca8a83ea7.png)
![screen shot 2017-11-20 at 15 48 14](https://user-images.githubusercontent.com/1818302/33040888-7f3e8820-ce0a-11e7-9265-8c3763a9d537.png)

## Testing Instructions

Once this branch is checked out, run:
```
yarn run build:library && npm pack
```
Now checkout `develop` on climate-change-lab, ensure node_modules is up to date with `yarn install` and then manually install the climate-change-components package with:
```
npm install ../climate-change-components/climate-change-components-0.2.1.tgz
```

You should now be able to select any of the indicators that use the historic_range param and get a default value selected for you when the indicator loads.

I had some trouble with my `apiHost` in lab set to `https://app.staging.climate.azavea.com`. Starting my local Climate API box on at least the current develop and setting `apiHost = http://localhost:8080` worked as a replacement.

Closes #12

2017-11-21 15:33 UTC, flibbertigibbet requested changes
Since the range defaults to the [most recent base year](https://github.com/azavea/climate-change-api/blob/4b757f42961ad2fe7af61525f57f217581d42760/django/climate_change_api/indicators/params.py#L251) and the base year options are known, it would be better to inspect `historicRangeOptions` and use the most recent year instead of hard-coding 1971.

2017-11-22 14:53 UTC, CloudNiner commented
Ok. I updated the PR to dynamically choose the default year. Unfortunately this has the side effect of making an additional pair of duplicate requests (although we can't always assume they're duplicates) just with the parameter added. I poked at seeing if I could clean up the request list quickly but its a broader problem across all indicators that this just makes worse for one case. I opened climate-change-lab#322 to address it.

2017-11-22 15:28 UTC, flibbertigibbet commented on src/lib/modules/charts/components/extra-params/historic.component.ts
> +              const latestHistoricRange = Math.max(...this.historicRangeOptions);
Ellipsis for an array builder, neat

2017-11-22 15:57 UTC, flibbertigibbet approved these changes
+1 on update to CHANGELOG

2017-11-22 16:24 UTC, merged

2017-11-22 16:41 UTC, flibbertigibbet commented on CHANGELOG.md
> +- PercentileHistoricComponent and HistoricComponent now automatically choose a sensible dropdown
Would have preferred something more specific than "sensible", i.e., explicitly match the default from the API.